name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Build Docker image
        run: docker build -t firstapp:latest .
      - name: Tag Docker image
        run: docker tag firstapp:latest ${{ secrets.DOCKERHUB_USER }}/firstapp:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/firstapp:latest
